[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Compiler settings
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

# Network settings
[rpc_endpoints]
xlayer = "https://rpc.xlayer.tech"
xlayer_testnet = "https://testrpc.xlayer.tech"

# Etherscan settings
[etherscan]
xlayer = { key = "${ETHERSCAN_API_KEY}", url = "https://www.oklink.com/api" }
xlayer_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://www.oklink.com/api" }

# Testing settings
[fuzz]
runs = 256
max_test_rejects = 65536
seed = "0x1"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false